// Authoritative product catalog.
//
// `amount_paise` is the single source of truth for pricing (Razorpay charges
// only what this file says). `kits.json` is generated by scripts/build-kits.mjs
// and carries the downloaded documents' metadata for the storefront.
const kits = require("./kits.json");

const PRODUCTS = {
  "dsa-decoder": {
    name: "The 40-Pattern DSA Decoder",
    amount_paise: 4900,
    anchor_paise: null,
    download_url: "/downloads/dsa-decoder.pdf"
  },
  "offer-stack": {
    name: "AI & LLM Systems Playbook",
    amount_paise: 9900,
    anchor_paise: null,
    download_url: "/downloads/offer-stack.pdf"
  },
  "company-vault": {
    name: "Database & Storage Deep Dive",
    amount_paise: 14900,
    anchor_paise: null,
    download_url: "/downloads/company-vault.pdf"
  },
  "system-design": {
    name: "System Design Interview Vault",
    amount_paise: 14900,
    anchor_paise: null,
    download_url: "/downloads/system-design.pdf"
  },
  "complete-system": {
    name: "The Complete Interview System",
    amount_paise: 29900,
    anchor_paise: 44600,
    download_url: "/downloads/complete-system.pdf"
  }
};

// Storefront-facing catalog: pricing plus the kit's generated metadata.
function publicCatalog() {
  return Object.entries(PRODUCTS).map(([sku, p]) => {
    const kit = kits[sku] || {};
    return {
      sku,
      name: p.name,
      amount: p.amount_paise,
      anchorPaise: p.anchor_paise,
      tagline: kit.tagline || "",
      pages: kit.pages || 0,
      chapters: kit.chapters || []
    };
  });
}

module.exports = { PRODUCTS, publicCatalog };
